### ISSUE TITLE
Multiple endpoints

### ISSUE THREAD

**Issue by trueqbit** [rimmartin/pion-ng#5]
It can be useful to have a server accepting connections on multiple endpoints (or addresses at the very least).

At the very least this comes in handy when you want to allow both ipv4 + ipv6.

Because tcp::server and http::server implement a lot of logic already it would be nice if this could be made available by the library itself.

**Comment by rimmartin** [comment]
Hi, I'll get active this weekend and catch up

**Comment by trueqbit** [comment]
@rimmartin You merged the corresponding PR... Are you happy with it? Can we close this ticket, or are there any further discussions needed?

**Comment by rimmartin** [comment]
Yes.

The other one conflicted; I did the merge steps github provided in terminal
